// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/consignment/consignment.proto

package consignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ShipplyService service

func NewShipplyServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ShipplyService service

type ShipplyService interface {
	CreateConsignment(ctx context.Context, in *Consignment, opts ...client.CallOption) (*Response, error)
	GetConsignments(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
}

type shipplyService struct {
	c    client.Client
	name string
}

func NewShipplyService(name string, c client.Client) ShipplyService {
	return &shipplyService{
		c:    c,
		name: name,
	}
}

func (c *shipplyService) CreateConsignment(ctx context.Context, in *Consignment, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ShipplyService.CreateConsignment", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipplyService) GetConsignments(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ShipplyService.GetConsignments", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShipplyService service

type ShipplyServiceHandler interface {
	CreateConsignment(context.Context, *Consignment, *Response) error
	GetConsignments(context.Context, *GetRequest, *Response) error
}

func RegisterShipplyServiceHandler(s server.Server, hdlr ShipplyServiceHandler, opts ...server.HandlerOption) error {
	type shipplyService interface {
		CreateConsignment(ctx context.Context, in *Consignment, out *Response) error
		GetConsignments(ctx context.Context, in *GetRequest, out *Response) error
	}
	type ShipplyService struct {
		shipplyService
	}
	h := &shipplyServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ShipplyService{h}, opts...))
}

type shipplyServiceHandler struct {
	ShipplyServiceHandler
}

func (h *shipplyServiceHandler) CreateConsignment(ctx context.Context, in *Consignment, out *Response) error {
	return h.ShipplyServiceHandler.CreateConsignment(ctx, in, out)
}

func (h *shipplyServiceHandler) GetConsignments(ctx context.Context, in *GetRequest, out *Response) error {
	return h.ShipplyServiceHandler.GetConsignments(ctx, in, out)
}
